"""updated document_chunks with cmetada column for langchain-postgres mapping

Revision ID: 3d51ff865c38
Revises: 92a7e48db1e0
Create Date: 2025-12-29 10:03:11.196510

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d51ff865c38"
down_revision: Union[str, Sequence[str], None] = "92a7e48db1e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("cmetadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "cmetadata")
    # ### end Alembic commands ###
